# Generated by Django 3.2.25 on 2024-11-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_type',
            field=models.FloatField(null=True),
        ),
    ]
